name: de-identification

on:
  push:
  pull_request:

jobs:
  deid-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Run de-identification scan
        run: python3 de-identification/scan.py
